import { test, expect } from '@playwright/test'

// The CSP ships as a per-page <meta> tag generated by Astro (security.csp),
// so the browser enforces it even against the local preview server. These
// tests fail if the policy blocks any resource a page actually needs.
test.describe('Content Security Policy', () => {
  const cspViolations = (messages: string[]) =>
    messages.filter(
      (m) => m.includes('Content Security Policy') || m.includes('Refused to'),
    )

  test('home page carries the CSP meta tag and loads without violations', async ({
    page,
  }) => {
    const consoleMessages: string[] = []
    page.on('console', (msg) => consoleMessages.push(msg.text()))

    await page.goto('/en/', { waitUntil: 'networkidle' })

    const csp = page.locator('meta[http-equiv="content-security-policy"]')
    await expect(csp).toHaveCount(1)
    const content = await csp.getAttribute('content')
    expect(content).toContain("default-src 'self'")
    expect(content).toContain('script-src')
    expect(content).toContain('style-src')

    expect(cspViolations(consoleMessages)).toEqual([])
  })

  test('a tool still hydrates and works under the CSP', async ({ page }) => {
    const consoleMessages: string[] = []
    page.on('console', (msg) => consoleMessages.push(msg.text()))

    await page.goto('/en/tools/base64/', { waitUntil: 'networkidle' })

    // Exercising the tool proves the island hydrated with CSP enforced
    await page.locator('textarea').first().fill('compliance')
    await page.getByRole('button', { name: 'Encode Base64' }).click()
    await expect(page.locator('textarea').nth(1)).toHaveValue('Y29tcGxpYW5jZQ==')

    expect(cspViolations(consoleMessages)).toEqual([])
  })

  test('security.txt is served', async ({ request }) => {
    const res = await request.get('/.well-known/security.txt')
    expect(res.status()).toBe(200)
    expect(await res.text()).toContain('Contact:')
  })
})
